name: Publish CLI to GitHub Releases

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore src/TWSort.csproj

      - name: Publish for Windows
        run: |
          dotnet publish src/TWSort.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish/windows-x64
          mv ./publish/windows-x64/twsort.exe ./publish/windows-x64/twsort-windows-x64.exe

      - name: Publish for Linux x64
        run: |
          dotnet publish src/TWSort.csproj -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o ./publish/linux-x64
          mv ./publish/linux-x64/twsort ./publish/linux-x64/twsort-linux-x64

      - name: Publish for Linux arm64
        run: |
          dotnet publish src/TWSort.csproj -c Release -r linux-arm64 --self-contained true -p:PublishSingleFile=true -o ./publish/linux-arm64
          mv ./publish/linux-arm64/twsort ./publish/linux-arm64/twsort-linux-arm64

      - name: Publish for macOS x64
        run: |
          dotnet publish src/TWSort.csproj -c Release -r osx-x64 --self-contained true -p:PublishSingleFile=true -o ./publish/macos-x64
          mv ./publish/macos-x64/twsort ./publish/macos-x64/twsort-macos-x64

      - name: Publish for macOS arm64
        run: |
          dotnet publish src/TWSort.csproj -c Release -r osx-arm64 --self-contained true -p:PublishSingleFile=true -o ./publish/macos-arm64
          mv ./publish/macos-arm64/twsort ./publish/macos-arm64/twsort-macos-arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            publish/windows-x64/twsort-windows-x64.exe
            publish/linux-x64/twsort-linux-x64
            publish/linux-arm64/twsort-linux-arm64
            publish/macos-x64/twsort-macos-x64
            publish/macos-arm64/twsort-macos-arm64
